#!/bin/bash

#SBATCH --job-name=retriever
#SBATCH --nodes=1
#SBATCH --gres=gpu:1
#SBATCH --time=0-12:00:00
#SBATCH --mem=80000MB
#SBATCH --cpus-per-task=8
#SBATCH --partition=P2
#SBATCH -o ./slurm_output/%x_%j.out
#SBATCH -e ./slurm_output/%x_%j.err
# python main_reranker.py --epochs=5 --bert_lr=2e-05 --lr=2e-05 --type_model=mixencoder --warmup_proportion=0.1 --inputmark --type_cands=mixed_negative --token_type --eval_batch_size=8 --save_dir=./models --num_layers=2 --num_heads=4 --cands_dir=./data/cands_top1024 --type_bert=base --B=2 --gradient_accumulation_steps=2 --gpus=0 --distill_training --alpha=0.2 --identity_bert --fixed_initial_weight --seed=12345 --resume_training --run_id=lkg1pfo4
# python main_reranker.py --epochs=5 --bert_lr=2e-05 --lr=2e-05 --type_model=mixencoder --warmup_proportion=0.1 --inputmark --type_cands=mixed_negative --token_type --eval_batch_size=8 --save_dir=./models --num_layers=2 --num_heads=4 --cands_dir=./data/cands_top1024 --type_bert=base --B=2 --gradient_accumulation_steps=2 --gpus=0 --distill_training --alpha=0.2 --identity_bert --fixed_initial_weight --seed=12 --resume_training --run_id=3ati9sra
# python main_reranker.py --epochs=5 --bert_lr=2e-05 --lr=2e-05 --type_model=mixencoder --warmup_proportion=0.1 --inputmark --type_cands=mixed_negative --token_type --eval_batch_size=8 --save_dir=./models --num_layers=2 --num_heads=4 --cands_dir=./data/cands_top1024 --type_bert=base --B=2 --gradient_accumulation_steps=2 --gpus=0 --distill_training --alpha=0.2 --identity_bert --fixed_initial_weight --seed=0 --resume_training --run_id=vtmzvicj
# python main_reranker.py --epochs=5 --bert_lr=2e-05 --lr=2e-05 --type_model=mixencoder --warmup_proportion=0.1 --inputmark --type_cands=mixed_negative --token_type --eval_batch_size=8 --save_dir=./models --num_layers=2 --num_heads=4 --cands_dir=./data/cands_top1024 --type_bert=base --B=2 --gradient_accumulation_steps=2 --gpus=0 --distill_training --alpha=0.2 --identity_bert --fixed_initial_weight --seed=123 --resume_training --run_id=fcc1t83m
python main_retriever.py --data_dir ./data --B 2 --gradient_accumulation_steps 2 --logging_steps 1000 --k 64 --epochs 4 --lr 0.00001 --num_cands 64 --type_cands mixed_negative --cands_ratio 0.5 --num_mention_vecs 16 --gpus 0 --type_model poly --num_entity_vecs 1 --too_large --en_hidden_path ./data --entity_bsz 1024 --mention_bsz 50 --store_en_hiddens --entity_bsz 1024 --mention_bsz 50 --seed=0 --resume_training --run_id=yn164kja
# python main_reranker.py --epochs=5 --bert_lr=2e-05 --lr=2e-05 --type_model=mixencoder --warmup_proportion=0.1 --inputmark --type_cands=mixed_negative --token_type --eval_batch_size=8 --save_dir=./models --num_layers=2 --num_heads=4 --cands_dir=./data/cands_top1024 --type_bert=base --B=2 --gradient_accumulation_steps=2 --gpus=0 --distill_training --alpha=0.2 --identity_bert --fixed_initial_weight --seed=12 --resume_training --run_id=3ati9sra
# python main_reranker.py --epochs=5 --bert_lr=2e-05 --lr=2e-05 --type_model=mixencoder --warmup_proportion=0.1 --inputmark --type_cands=mixed_negative --token_type --eval_batch_size=8 --save_dir=./models --num_layers=2 --num_heads=4 --cands_dir=./data/cands_top1024 --type_bert=base --B=2 --gradient_accumulation_steps=2 --gpus=0 --distill_training --alpha=0.2 --identity_bert --fixed_initial_weight --seed=0
# python main_reranker.py --epochs=5 --bert_lr=2e-05 --lr=2e-05 --type_model=mixencoder --warmup_proportion=0.1 --inputmark --type_cands=mixed_negative --token_type --eval_batch_size=8 --save_dir=./models --num_layers=2 --num_heads=4 --cands_dir=./data/cands_top1024 --type_bert=base --B=2 --gradient_accumulation_steps=2 --gpus=0 --distill_training --alpha=0.2 --identity_bert --fixed_initial_weight --seed=0 --resume_training --run_id=yn164kja
# python main_reranker.py --epochs=5 --bert_lr=2e-05 --lr=2e-05 --type_model=deformer --warmup_proportion=0.1 --inputmark --type_cands=mixed_negative --token_type --eval_batch_size=8 --save_dir=./models --num_layers=2 --num_heads=4 --cands_dir=./data/cands_top1024 --type_bert=base --B=2 --gradient_accumulation_steps=2 --gpus=0 --distill_training --alpha=0.2 --identity_bert --fixed_initial_weight --seed=12345
# python main_retriever.py --data_dir ./data --B 2 --gradient_accumulation_steps 2 --logging_steps 1000 --k 64 --epochs 4 --lr 0.00001 --num_cands 64 --type_cands mixed_negative --cands_ratio 0.5 --num_mention_vecs 16 --gpus 0 --type_model poly --num_entity_vecs 1 --too_large --en_hidden_path ./data --entity_bsz 1024 --mention_bsz 50 --store_en_hiddens --entity_bsz 1024 --mention_bsz 50 --seed=12
#

# python main_reranker.py --epochs=5 --bert_lr=5e-05 --lr=5e-05 --type_model=deformer --warmup_proportion=0.1 --inputmark --type_cands=mixed_negative --token_type --eval_batch_size=8 --save_dir=./models --num_layers=2 --num_heads=4 --cands_dir=./data/cands_top1024 --type_bert=base --B=2 --gradient_accumulation_steps=2 --gpus=0 --distill_training --alpha=0.2 --identity_bert --fixed_initial_weight --resume_training --run_id=uvko7gqa

# python main_reranker.py --epochs=5 --bert_lr=2e-05 --lr=2e-05 --type_model=deformer --warmup_proportion=0.1 --inputmark --type_cands=mixed_negative --token_type --eval_batch_size=8 --save_dir=./models --num_layers=2 --num_heads=4 --cands_dir=./data/cands_top1024 --type_bert=base --B=2 --gradient_accumulation_steps=2 --gpus=0 --distill_training --alpha=0.2 --identity_bert --fixed_initial_weight --resume_training --run_id=uvko7gqa
# python main_reranker.py --epochs=5 --bert_lr=1e-05 --lr=1e-05 --type_model=deformer --warmup_proportion=0.1 --inputmark --type_cands=mixed_negative --token_type --eval_batch_size=8 --save_dir=./models --num_layers=2 --num_heads=4 --cands_dir=./data/cands_top1024 --type_bert=base --B=2 --gradient_accumulation_steps=2 --gpus=0 --distill_training --alpha=0.2 --identity_bert --fixed_initial_weight --resume_training --run_id=bkod9sps
# python main_reranker.py --epochs=5 --bert_lr=1e-05 --lr=1e-05 --type_model=mixencoder --warmup_proportion=0.1 --inputmark --type_cands=mixed_negative --token_type --eval_batch_size=8 --save_dir=./models --num_layers=2 --num_heads=4 --cands_dir=./data/cands_top1024 --type_bert=base --B=2 --gradient_accumulation_steps=2 --gpus=0 --distill_training --alpha=0.2 --identity_bert --fixed_initial_weight --resume_training --run_id=vlrp4q2n